diff --git Makefile Makefile
index 964889532..37fcca37a 100644
--- Makefile
+++ Makefile
@@ -73,7 +73,7 @@ image: clean-image ## Build image for a particular arch.
 		--build-arg TARGETARCH="$(ARCH)" \
 		--build-arg COMMIT_SHA="$(COMMIT_SHA)" \
 		--build-arg BUILD_ID="$(BUILD_ID)" \
-		-t $(REGISTRY)/controller:$(TAG) rootfs
+		-t $(REGISTRY)/ingress-nginx-controller:$(TAG) rootfs
 
 .PHONY: gosec
 gosec:
@@ -93,8 +93,8 @@ image-chroot: clean-chroot-image ## Build image for a particular arch.
 
 .PHONY: clean-image
 clean-image: ## Removes local image
-	echo "removing old image $(REGISTRY)/controller:$(TAG)"
-	@docker rmi -f $(REGISTRY)/controller:$(TAG) || true
+	echo "removing old image $(REGISTRY)/ingress-nginx-controller:$(TAG)"
+	@docker rmi -f $(REGISTRY)/ingress-nginx-controller:$(TAG) || true
 
 
 .PHONY: clean-chroot-image
